[package]
name = "asb-options"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3", default-features = false }
strum = "0.22.0"
strum_macros = "0.22.0"