[package]
name = "authdb-trait"
version = "0.1.0"
edition = "2021"
authors = ["Chenxing Li <ChenxingLi@users.noreply.github.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvdb = { workspace = true }